In [17]:
import numpy as np

In [2]:
## concatenation 

arr1=np.array([1,2,3,4])
arr2=np.array([4,6,7,8])


In [3]:
arr1,arr2

(array([1, 2, 3, 4]), array([4, 6, 7, 8]))

In [4]:
arr3=np.concatenate((arr1,arr2))

In [5]:
arr3

array([1, 2, 3, 4, 4, 6, 7, 8])

In [6]:
arr3=np.concatenate((arr1,arr2),axis=0)

In [7]:
arr3

array([1, 2, 3, 4, 4, 6, 7, 8])

In [8]:
arr5=np.array([[1,2,3],[4,5,6]])
arr6=np.array([[7,8,9],[10,11,12]])



In [9]:
arr=np.concatenate((arr5,arr6),axis=1)

In [10]:
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:
arr=np.vstack((arr5,arr6))

In [12]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr=np.hstack((arr5,arr6))
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [14]:
arr=np.dstack((arr5,arr6))
print(arr)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [15]:
array7=np.array([[1,2,3],
                [4,5,6]])
array8=np.array([[2,2,4]])  
arr9=np.vstack((array7,array8))
print(arr9)              

[[1 2 3]
 [4 5 6]
 [2 2 4]]


In [16]:
array10=np.array([[10],[10]])
array10

array([[10],
       [10]])