In [41]:
import numpy as np


In [42]:
array1=np.linspace(-np.pi,np.pi,10)

In [43]:
print(array1)

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]


In [44]:
sin_val=np.sin(array1)
print(sin_val)

[-1.22464680e-16 -6.42787610e-01 -9.84807753e-01 -8.66025404e-01
 -3.42020143e-01  3.42020143e-01  8.66025404e-01  9.84807753e-01
  6.42787610e-01  1.22464680e-16]


In [45]:
sin_val=np.round(sin_val,3)
print(sin_val)

[-0.    -0.643 -0.985 -0.866 -0.342  0.342  0.866  0.985  0.643  0.   ]


array1=np.array([1,2,3,4,5,6,7])
mean=np.mean(array1)
print(mean)

In [46]:
array1=np.array([1,2,3,4,5])
mean=np.mean(array1)
print(mean)

3.0


In [47]:
array2=np.array([[6,7,8,10],
                 [8,3,5,12],
                 [10,23,4,6],
                 [10,12,16,18]])
array2                 

array([[ 6,  7,  8, 10],
       [ 8,  3,  5, 12],
       [10, 23,  4,  6],
       [10, 12, 16, 18]])

In [48]:
mean=np.mean(array2)

In [49]:
print(mean)

9.875


In [50]:
mean_1=np.mean(array2,axis=0)
mean_1
print(mean_1)

[ 8.5  11.25  8.25 11.5 ]


In [51]:
mean_1=np.mean(array2,axis=0)
print(mean_1)

[ 8.5  11.25  8.25 11.5 ]


In [52]:
### random numbers in numpy
rand_array1=np.random.rand(4)
rand_array1

array([0.61861159, 0.24560959, 0.511663  , 0.00062036])

In [53]:
rand_array1=np.random.rand(4,4)
print(rand_array1)

[[0.15710439 0.50478772 0.31834302 0.56972379]
 [0.86639828 0.03096793 0.3108324  0.60682325]
 [0.45169551 0.9296506  0.12971101 0.92194829]
 [0.76135019 0.54400454 0.29398268 0.5228765 ]]


In [54]:
randint_array=np.random.randint(10,20,
        size=(4,5))
print(randint_array)

[[13 14 18 16 11]
 [10 18 10 11 17]
 [10 11 11 12 18]
 [10 14 17 10 19]]


In [55]:
array_1=np.random.randint(10,51,size=(5,6))
array_1

array([[17, 14, 33, 15, 32, 45],
       [22, 26, 33, 31, 13, 28],
       [49, 35, 41, 45, 31, 30],
       [49, 34, 11, 16, 25, 11],
       [14, 31, 11, 45, 20, 31]], dtype=int32)

In [56]:
array_first,array_second=np.split(array_1,[3],axis=0)

In [57]:
array_first,array_second

(array([[17, 14, 33, 15, 32, 45],
        [22, 26, 33, 31, 13, 28],
        [49, 35, 41, 45, 31, 30]], dtype=int32),
 array([[49, 34, 11, 16, 25, 11],
        [14, 31, 11, 45, 20, 31]], dtype=int32))

In [58]:
array_first

array([[17, 14, 33, 15, 32, 45],
       [22, 26, 33, 31, 13, 28],
       [49, 35, 41, 45, 31, 30]], dtype=int32)

In [59]:
array_columnpart1,array_columnpart2=np.split(array_1,[3],axis=0)
array_columnpart1,array_columnpart2

(array([[17, 14, 33, 15, 32, 45],
        [22, 26, 33, 31, 13, 28],
        [49, 35, 41, 45, 31, 30]], dtype=int32),
 array([[49, 34, 11, 16, 25, 11],
        [14, 31, 11, 45, 20, 31]], dtype=int32))

In [60]:
array_columnpart1,array_columnpart2=np.split(array_1,[3],axis=1)
array_columnpart1,array_columnpart2

(array([[17, 14, 33],
        [22, 26, 33],
        [49, 35, 41],
        [49, 34, 11],
        [14, 31, 11]], dtype=int32),
 array([[15, 32, 45],
        [31, 13, 28],
        [45, 31, 30],
        [16, 25, 11],
        [45, 20, 31]], dtype=int32))

In [61]:
array_columnpart1,array_columnpart2,array_columnpart3=np.split(array_1,[2,3],axis=1)
array_columnpart1,array_columnpart2,array_columnpart3

(array([[17, 14],
        [22, 26],
        [49, 35],
        [49, 34],
        [14, 31]], dtype=int32),
 array([[33],
        [33],
        [41],
        [11],
        [11]], dtype=int32),
 array([[15, 32, 45],
        [31, 13, 28],
        [45, 31, 30],
        [16, 25, 11],
        [45, 20, 31]], dtype=int32))

In [62]:
array_columnpart1.shape

(5, 2)

In [63]:
array_columnpart2.shape

(5, 1)

In [64]:
array_columnpart3.shape

(5, 3)

In [65]:
iris_array=np.genfromtxt(r"C:\Users\Piyush Deo\Desktop\ml_env\iris.txt",delimiter=',')

In [66]:
print(iris_array)

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [5.7 4.4 1.5 0.4 nan]
 [5.4 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5.  3.5 1.3 0.3 nan]
 [4.5 2.3 1.3 0.3 nan]
 [4.4 3.2 1.3 0.2 nan]
 [5.  3.5 1

In [67]:
iris_array=np.genfromtxt(r"C:\Users\Piyush Deo\Desktop\ml_env\iris.txt",delimiter=',',dtype='str')
print(iris_array)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

In [68]:
iris_array=np.genfromtxt(r"C:\Users\Piyush Deo\Desktop\ml_env\iris.txt",delimiter=',',dtype='int')
print(iris_array)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1

In [69]:
iris_array=np.genfromtxt(r"C:\Users\Piyush Deo\Desktop\ml_env\iris.txt",delimiter=',',dtype='str')
print(iris_array)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

In [70]:
features,labels=np.split(iris_array,[4],axis=1)
features.shape
labels.shape

(150, 1)

In [71]:
labels.shape

(150, 1)

In [72]:
features.shape

(150, 4)

In [73]:
print(features,labels)

[['5.1' '3.5' '1.4' '0.2']
 ['4.9' '3.0' '1.4' '0.2']
 ['4.7' '3.2' '1.3' '0.2']
 ['4.6' '3.1' '1.5' '0.2']
 ['5.0' '3.6' '1.4' '0.2']
 ['5.4' '3.9' '1.7' '0.4']
 ['4.6' '3.4' '1.4' '0.3']
 ['5.0' '3.4' '1.5' '0.2']
 ['4.4' '2.9' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.4' '3.7' '1.5' '0.2']
 ['4.8' '3.4' '1.6' '0.2']
 ['4.8' '3.0' '1.4' '0.1']
 ['4.3' '3.0' '1.1' '0.1']
 ['5.8' '4.0' '1.2' '0.2']
 ['5.7' '4.4' '1.5' '0.4']
 ['5.4' '3.9' '1.3' '0.4']
 ['5.1' '3.5' '1.4' '0.3']
 ['5.7' '3.8' '1.7' '0.3']
 ['5.1' '3.8' '1.5' '0.3']
 ['5.4' '3.4' '1.7' '0.2']
 ['5.1' '3.7' '1.5' '0.4']
 ['4.6' '3.6' '1.0' '0.2']
 ['5.1' '3.3' '1.7' '0.5']
 ['4.8' '3.4' '1.9' '0.2']
 ['5.0' '3.0' '1.6' '0.2']
 ['5.0' '3.4' '1.6' '0.4']
 ['5.2' '3.5' '1.5' '0.2']
 ['5.2' '3.4' '1.4' '0.2']
 ['4.7' '3.2' '1.6' '0.2']
 ['4.8' '3.1' '1.6' '0.2']
 ['5.4' '3.4' '1.5' '0.4']
 ['5.2' '4.1' '1.5' '0.1']
 ['5.5' '4.2' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.0' '3.2' '1.2' '0.2']
 ['5.5' '3.5' '1.3' '0.2']
 

In [74]:
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

In [75]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [76]:
features,labels=np.split(iris_array,[4],axis=1)
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [77]:
features=features.astype(float)

In [78]:
iris_array=np.genfromtxt(r"C:\Users\Piyush Deo\Desktop\ml_env\iris.txt",delimiter=',',dtype='str')
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [79]:
mean_feature=np.mean(features,axis=0)
mean_feature

array([5.84333333, 3.054     , 3.75866667, 1.19866667])